// =============================================
// PERGUNTAS DO JOGO (um bloco por idioma)
// As chaves das categorias (engracadas, casal, gerais)
// são as mesmas em todos os idiomas.
// =============================================
const DECK = {

  // ---------------- PORTUGUÊS ----------------
  pt: {
    engracadas: [
      "Qual foi a coisa mais estranha que você já comeu achando que era outra coisa?",
      "Se você tivesse que trocar de nome amanhã, qual nome escolheria?",
      "Qual é a mentira mais boba que você já contou pros seus pais?",
      "Se seu pet pudesse falar, qual seria a primeira coisa que ele diria sobre você?",
      "Qual superpoder inútil você gostaria de ter?",
      "Já dançou sozinho(a) na frente do espelho fingindo ser cantor(a)? Qual música?",
      "Qual foi seu apelido mais vergonhoso na infância?",
      "Se você fosse um tempero, qual seria e por quê?",
      "Qual é a coisa mais aleatória que te faz rir até hoje?",
      "Se tivesse que anunciar um produto ridículo na TV, qual seria?",
      "Qual foi a pior desculpa que você já usou para faltar em algo?",
      "Se você acordasse amanhã como um personagem de desenho animado, qual seria?",
      "Qual é o seu talento mais inútil?",
      "Já fingiu entender um assunto numa conversa? Qual foi?",
      "Se pudesse trocar de corpo com um animal por um dia, qual escolheria?",
      "Qual foi o pior corte de cabelo que você já teve?",
      "Se você fosse expulso de um país, qual seria o motivo mais provável?",
      "Qual comida você defende com unhas e dentes mesmo todo mundo achando ruim?",
      "Já caiu andando na rua sem ninguém perto? Conta a história.",
      "Se sua vida fosse um reality show, qual seria o nome?",
      "Qual foi a pior compra por impulso que você já fez?",
      "Se você pudesse ter um jingle pessoal tocando toda vez que entra em um lugar, qual seria a música?",
      "Qual foi a maior vergonha que você já passou em público?",
      "Se seus amigos tivessem que te descrever em um emoji só, qual seria?",
      "Qual foi a desculpa mais criativa que alguém já te deu?",
      "Se você fosse contratado(a) para um emprego bizarro, qual seria o ideal pra você?",
      "Qual foi o pior presente que você já ganhou e teve que fingir gostar?",
      "Se pudesse inventar uma nova palavra, qual seria e o que significaria?",
      "Qual foi a última vez que você riu tanto que quase chorou? O que aconteceu?",
      "Se você tivesse que escolher um som para representar sua personalidade, qual seria?",
      "Qual foi o pior conselho que alguém já te deu levando a sério?",
      "Se pudesse ser reconhecido(a) por uma habilidade estranha, qual escolheria?",
      "Qual foi a coisa mais boba que você já discutiu com alguém?",
      "Se você fosse um filtro de rede social, qual seria o efeito?",
      "Qual foi a experiência mais constrangedora numa entrevista de emprego ou primeiro dia de trabalho?",
      "Se pudesse trocar sua voz pela de alguém famoso por um dia, quem escolheria?",
      "Qual foi o pior apelido que já tentaram te dar e não pegou?",
      "Se você ganhasse um troféu por algo bobo que faz bem, qual seria?",
      "Qual foi a mentira mais absurda que você já acreditou?",
      "Se pudesse ter qualquer animal de estimação exótico, qual escolheria e como chamaria?"
    ],
    casal: [
      "Qual foi o momento em que você percebeu que estava apaixonado(a) por mim?",
      "Qual é a nossa memória juntos que mais te faz sorrir?",
      "O que você mais admira em mim que talvez eu nem perceba?",
      "Se pudéssemos viajar para qualquer lugar do mundo juntos agora, para onde iríamos?",
      "Qual foi nosso encontro favorito até hoje?",
      "O que te faz sentir mais amado(a) por mim no dia a dia?",
      "Qual é um sonho que você quer realizar comigo no futuro?",
      "Existe algo que você gostaria que fizéssemos juntos mas nunca fizemos?",
      "Qual música te lembra de nós dois?",
      "O que você achou de mim no nosso primeiro encontro?",
      "Qual é a coisa mais engraçada que já aconteceu entre a gente?",
      "Como você imagina nossa vida daqui a 10 anos?",
      "Qual foi o momento em que você sentiu que podia confiar 100% em mim?",
      "O que você mudaria com carinho em mim, se pudesse?",
      "Qual é a nossa tradição de casal favorita, se tivermos uma?",
      "O que você sente que aprendeu comigo desde que estamos juntos?",
      "Qual é o meu jeito de demonstrar carinho que você mais gosta?",
      "Se pudéssemos reviver um dia nosso juntos, qual escolheria?",
      "O que você espera que a gente nunca perca com o tempo?",
      "Qual foi a declaração ou gesto mais romântico que já rolou entre a gente?",
      "Qual foi o momento em que você sentiu mais orgulho de mim?",
      "O que você acha que só eu consigo fazer você sentir?",
      "Qual é a maior diferença entre nós que você acha que nos complementa?",
      "Se pudéssemos criar uma tradição nova só nossa, qual seria?",
      "O que te surpreendeu em mim depois que começamos a namorar?",
      "Qual foi um momento difícil que enfrentamos juntos e que nos deixou mais fortes?",
      "O que você mais gosta de fazer comigo no dia a dia, mesmo sendo algo simples?",
      "Se você pudesse me presentear com uma experiência, não um objeto, qual seria?",
      "Qual palavra você usaria para descrever a nossa relação hoje?",
      "O que você espera que eu nunca mude?",
      "Qual foi a primeira coisa que você notou em mim?",
      "Se pudéssemos morar em qualquer lugar juntos, onde seria e por quê?",
      "O que te faz sentir seguro(a) na nossa relação?",
      "Qual é um objetivo que você gostaria que conquistássemos juntos este ano?",
      "O que você acha que aprendemos um com o outro até agora?",
      "Se tivéssemos que escrever uma carta pro nosso 'eu' daqui a 5 anos, o que diria?",
      "Qual foi um gesto pequeno meu que teve um grande significado pra você?",
      "O que te faz sentir mais próximo(a) de mim?",
      "Se pudéssemos reviver nosso primeiro 'eu te amo', como seria diferente ou igual?",
      "O que você mais espera da nossa próxima fase juntos?"
    ],
    gerais: [
      "Se você pudesse aprender qualquer habilidade instantaneamente, qual escolheria?",
      "Qual foi a decisão mais corajosa que você já tomou?",
      "O que te deixa mais animado(a) nos dias de hoje?",
      "Se dinheiro não fosse problema, o que você faria da vida?",
      "Qual livro, filme ou série mudou sua forma de ver o mundo?",
      "Qual é o seu maior medo hoje?",
      "Se pudesse jantar com qualquer pessoa, viva ou morta, quem seria?",
      "Qual conselho você daria para você mesmo(a) há 5 anos?",
      "O que te faz sentir mais vivo(a)?",
      "Qual foi o momento mais desafiador da sua vida até agora?",
      "Se pudesse morar em qualquer lugar do mundo, onde seria?",
      "Qual é uma crença que você tinha e mudou de opinião?",
      "O que você faria num dia sem nenhuma responsabilidade?",
      "Qual é a coisa que você mais valoriza numa amizade?",
      "Se pudesse voltar no tempo, qual momento reviveria?",
      "Qual é o seu maior sonho profissional?",
      "O que te dá mais paz?",
      "Qual foi a melhor surpresa que você já recebeu?",
      "Se você pudesse mudar uma coisa no mundo, o que seria?",
      "Qual é a lição mais importante que a vida já te ensinou?",
      "O que te motiva a levantar da cama todos os dias?",
      "Qual foi um momento em que você teve que sair da sua zona de conforto?",
      "Se pudesse escolher uma época da história pra viver, qual seria?",
      "O que você considera sucesso na vida?",
      "Qual foi a melhor lição que um erro te ensinou?",
      "Se pudesse ter uma conversa com você mesmo(a) daqui a 20 anos, o que perguntaria?",
      "O que você faz quando precisa recarregar as energias?",
      "Qual é uma habilidade que você gostaria de desenvolver mais?",
      "Se pudesse resolver um problema do mundo, qual escolheria?",
      "O que te inspira nas pessoas que você admira?",
      "Qual foi um momento em que você teve que ser corajoso(a) sozinho(a)?",
      "Se pudesse recomeçar algo do zero, o que seria?",
      "O que significa liberdade para você?",
      "Qual foi a melhor aula que a vida te deu fora da escola?",
      "Se você pudesse escolher sua própria idade para sempre, qual seria?",
      "O que você gostaria que as pessoas entendessem melhor sobre você?",
      "Qual foi um momento em que você se sentiu realmente orgulhoso(a) de si mesmo(a)?",
      "Se pudesse ter certeza de uma coisa sobre o futuro, o que gostaria de saber?",
      "O que te faz sentir grato(a) hoje?",
      "Qual conselho você daria para alguém que está começando algo novo?"
    ]
  },

  // ---------------- FRANÇAIS ----------------
  fr: {
    engracadas: [
      "Quelle est la chose la plus bizarre que tu aies mangée en pensant que c’était autre chose ?",
      "Si tu devais changer de prénom demain, lequel choisirais-tu ?",
      "Quel est le mensonge le plus bête que tu aies raconté à tes parents ?",
      "Si ton animal pouvait parler, quelle serait la première chose qu’il dirait sur toi ?",
      "Quel super-pouvoir inutile aimerais-tu avoir ?",
      "As-tu déjà dansé devant le miroir en faisant semblant d’être une star ? Sur quelle chanson ?",
      "Quel était ton surnom le plus gênant pendant ton enfance ?",
      "Si tu étais une épice, laquelle serais-tu et pourquoi ?",
      "Quelle est la chose la plus absurde qui te fait encore rire aujourd’hui ?",
      "Si tu devais présenter un produit ridicule à la télé, lequel ce serait ?",
      "Quelle est la pire excuse que tu aies utilisée pour ne pas aller quelque part ?",
      "Si tu te réveillais demain dans la peau d’un personnage de dessin animé, lequel serait-ce ?",
      "Quel est ton talent le plus inutile ?",
      "As-tu déjà fait semblant de comprendre un sujet pendant une conversation ? Lequel ?",
      "Si tu pouvais échanger ton corps avec un animal pendant une journée, lequel choisirais-tu ?",
      "Quelle a été ta pire coupe de cheveux ?",
      "Si tu te faisais expulser d’un pays, quelle serait la raison la plus probable ?",
      "Quel plat défends-tu bec et ongles alors que tout le monde le trouve mauvais ?",
      "T’est-il déjà arrivé de tomber dans la rue sans personne autour ? Raconte.",
      "Si ta vie était une émission de téléréalité, comment s’appellerait-elle ?",
      "Quel a été ton pire achat impulsif ?",
      "Si tu avais un jingle personnel qui jouait chaque fois que tu entres quelque part, quelle serait la musique ?",
      "Quelle a été ta plus grosse honte en public ?",
      "Si tes amis devaient te décrire avec un seul emoji, lequel serait-ce ?",
      "Quelle est l’excuse la plus créative qu’on t’ait jamais donnée ?",
      "Si on t’embauchait pour un métier bizarre, lequel serait fait pour toi ?",
      "Quel est le pire cadeau que tu aies reçu en faisant semblant de l’aimer ?",
      "Si tu pouvais inventer un nouveau mot, quel serait-il et que voudrait-il dire ?",
      "À quand remonte la dernière fois où tu as ri aux larmes ? Que s’est-il passé ?",
      "Si tu devais choisir un son pour représenter ta personnalité, lequel serait-ce ?",
      "Quel est le pire conseil qu’on t’ait donné très sérieusement ?",
      "Pour quel talent étrange aimerais-tu être célèbre ?",
      "Quelle est la dispute la plus bête que tu aies jamais eue ?",
      "Si tu étais un filtre de réseau social, quel serait l’effet ?",
      "Quelle a été ta situation la plus gênante lors d’un entretien d’embauche ou d’un premier jour de travail ?",
      "Si tu pouvais emprunter la voix d’une célébrité pendant une journée, laquelle choisirais-tu ?",
      "Quel est le pire surnom qu’on a essayé de te donner et qui n’a jamais pris ?",
      "Si tu gagnais un trophée pour un truc bête que tu fais bien, ce serait pour quoi ?",
      "Quel est le mensonge le plus absurde auquel tu aies cru ?",
      "Si tu pouvais avoir n’importe quel animal exotique, lequel choisirais-tu et comment l’appellerais-tu ?"
    ],
    casal: [
      "À quel moment as-tu compris que tu étais amoureux(se) de moi ?",
      "Quel est notre souvenir ensemble qui te fait le plus sourire ?",
      "Qu’est-ce que tu admires le plus chez moi, que je ne remarque peut-être même pas ?",
      "Si on pouvait partir n’importe où dans le monde maintenant, où irait-on ?",
      "Quel a été notre rendez-vous préféré jusqu’ici ?",
      "Qu’est-ce qui te fait te sentir le plus aimé(e) par moi au quotidien ?",
      "Quel rêve aimerais-tu réaliser avec moi dans le futur ?",
      "Y a-t-il quelque chose que tu aimerais qu’on fasse ensemble mais qu’on n’a jamais fait ?",
      "Quelle chanson te fait penser à nous deux ?",
      "Qu’as-tu pensé de moi lors de notre premier rendez-vous ?",
      "Quelle est la chose la plus drôle qui nous soit arrivée ?",
      "Comment imagines-tu notre vie dans 10 ans ?",
      "À quel moment as-tu senti que tu pouvais me faire confiance à 100 % ?",
      "Qu’est-ce que tu changerais chez moi, avec tendresse, si tu le pouvais ?",
      "Quelle est notre tradition de couple préférée, si on en a une ?",
      "Qu’as-tu l’impression d’avoir appris avec moi depuis qu’on est ensemble ?",
      "Quelle est ma façon de montrer mon affection que tu préfères ?",
      "Si on pouvait revivre une de nos journées ensemble, laquelle choisirais-tu ?",
      "Qu’est-ce que tu espères qu’on ne perde jamais avec le temps ?",
      "Quelle a été la déclaration ou le geste le plus romantique entre nous ?",
      "À quel moment as-tu été le plus fier(ère) de moi ?",
      "Selon toi, qu’est-ce que moi seul(e) arrive à te faire ressentir ?",
      "Quelle est la plus grande différence entre nous qui, selon toi, nous complète ?",
      "Si on pouvait créer une nouvelle tradition rien qu’à nous, laquelle serait-ce ?",
      "Qu’est-ce qui t’a surpris(e) chez moi après qu’on a commencé à sortir ensemble ?",
      "Quel moment difficile avons-nous traversé ensemble qui nous a rendus plus forts ?",
      "Qu’est-ce que tu préfères faire avec moi au quotidien, même si c’est tout simple ?",
      "Si tu pouvais m’offrir une expérience plutôt qu’un objet, laquelle serait-ce ?",
      "Quel mot utiliserais-tu pour décrire notre relation aujourd’hui ?",
      "Qu’est-ce que tu espères que je ne change jamais ?",
      "Quelle est la première chose que tu as remarquée chez moi ?",
      "Si on pouvait vivre n’importe où ensemble, où serait-ce et pourquoi ?",
      "Qu’est-ce qui te fait te sentir en sécurité dans notre relation ?",
      "Quel objectif aimerais-tu qu’on atteigne ensemble cette année ?",
      "Selon toi, qu’est-ce qu’on a appris l’un de l’autre jusqu’ici ?",
      "Si on devait écrire une lettre à nous-mêmes dans 5 ans, qu’est-ce qu’on dirait ?",
      "Quel petit geste de ma part a eu une grande signification pour toi ?",
      "Qu’est-ce qui te fait te sentir le plus proche de moi ?",
      "Si on pouvait revivre notre premier « je t’aime », qu’est-ce qui serait différent ou pareil ?",
      "Qu’attends-tu le plus de notre prochaine étape ensemble ?"
    ],
    gerais: [
      "Si tu pouvais apprendre n’importe quelle compétence instantanément, laquelle choisirais-tu ?",
      "Quelle est la décision la plus courageuse que tu aies prise ?",
      "Qu’est-ce qui t’enthousiasme le plus en ce moment ?",
      "Si l’argent n’était pas un problème, que ferais-tu de ta vie ?",
      "Quel livre, film ou série a changé ta façon de voir le monde ?",
      "Quelle est ta plus grande peur aujourd’hui ?",
      "Si tu pouvais dîner avec n’importe qui, vivant ou mort, qui choisirais-tu ?",
      "Quel conseil te donnerais-tu à toi-même il y a 5 ans ?",
      "Qu’est-ce qui te fait te sentir le plus vivant(e) ?",
      "Quel a été le moment le plus difficile de ta vie jusqu’ici ?",
      "Si tu pouvais vivre n’importe où dans le monde, où serait-ce ?",
      "Sur quelle croyance as-tu changé d’avis avec le temps ?",
      "Que ferais-tu d’une journée sans aucune responsabilité ?",
      "Qu’est-ce que tu valorises le plus dans une amitié ?",
      "Si tu pouvais remonter le temps, quel moment revivrais-tu ?",
      "Quel est ton plus grand rêve professionnel ?",
      "Qu’est-ce qui t’apporte le plus de paix ?",
      "Quelle est la plus belle surprise que tu aies reçue ?",
      "Si tu pouvais changer une chose dans le monde, ce serait quoi ?",
      "Quelle est la leçon la plus importante que la vie t’ait apprise ?",
      "Qu’est-ce qui te motive à te lever chaque matin ?",
      "À quel moment as-tu dû sortir de ta zone de confort ?",
      "Si tu pouvais choisir une époque de l’histoire où vivre, laquelle serait-ce ?",
      "Qu’est-ce que la réussite, pour toi ?",
      "Quelle est la meilleure leçon qu’une erreur t’ait apprise ?",
      "Si tu pouvais parler à toi-même dans 20 ans, que lui demanderais-tu ?",
      "Que fais-tu quand tu as besoin de recharger tes batteries ?",
      "Quelle compétence aimerais-tu développer davantage ?",
      "Si tu pouvais résoudre un problème du monde, lequel choisirais-tu ?",
      "Qu’est-ce qui t’inspire chez les personnes que tu admires ?",
      "À quel moment as-tu dû faire preuve de courage sans l’aide de personne ?",
      "Si tu pouvais recommencer quelque chose de zéro, ce serait quoi ?",
      "Que signifie la liberté pour toi ?",
      "Quelle est la meilleure leçon que la vie t’ait donnée en dehors de l’école ?",
      "Si tu pouvais garder le même âge pour toujours, lequel choisirais-tu ?",
      "Qu’aimerais-tu que les gens comprennent mieux à ton sujet ?",
      "À quel moment as-tu été vraiment fier(ère) de toi ?",
      "Si tu pouvais être sûr(e) d’une chose sur l’avenir, que voudrais-tu savoir ?",
      "Pour quoi es-tu reconnaissant(e) aujourd’hui ?",
      "Quel conseil donnerais-tu à quelqu’un qui commence quelque chose de nouveau ?"
    ]
  },

  // ---------------- ENGLISH ----------------
  en: {
    engracadas: [
      "What’s the weirdest thing you’ve ever eaten thinking it was something else?",
      "If you had to change your name tomorrow, what would you pick?",
      "What’s the silliest lie you ever told your parents?",
      "If your pet could talk, what’s the first thing it would say about you?",
      "What useless superpower would you love to have?",
      "Have you ever danced in front of the mirror pretending to be a pop star? To what song?",
      "What was your most embarrassing childhood nickname?",
      "If you were a spice, which one would you be and why?",
      "What’s the most random thing that still makes you laugh?",
      "If you had to advertise a ridiculous product on TV, what would it be?",
      "What’s the worst excuse you’ve ever used to get out of something?",
      "If you woke up tomorrow as a cartoon character, who would you be?",
      "What’s your most useless talent?",
      "Have you ever pretended to understand a topic in a conversation? What was it?",
      "If you could swap bodies with an animal for a day, which would you choose?",
      "What’s the worst haircut you’ve ever had?",
      "If you got kicked out of a country, what would be the most likely reason?",
      "What food do you defend to the death even though everyone else hates it?",
      "Have you ever fallen in the street with nobody around? Tell the story.",
      "If your life were a reality show, what would it be called?",
      "What’s the worst impulse buy you’ve ever made?",
      "If you had a personal theme song that played every time you walked into a room, what would it be?",
      "What’s the most embarrassing thing that’s happened to you in public?",
      "If your friends had to describe you with a single emoji, which one would it be?",
      "What’s the most creative excuse someone has ever given you?",
      "If you were hired for a bizarre job, what would be the perfect one for you?",
      "What’s the worst gift you’ve ever received and had to pretend to like?",
      "If you could invent a new word, what would it be and what would it mean?",
      "When was the last time you laughed so hard you almost cried? What happened?",
      "If you had to pick a sound to represent your personality, what would it be?",
      "What’s the worst advice someone has given you with a straight face?",
      "If you could be famous for a strange skill, what would you pick?",
      "What’s the silliest thing you’ve ever argued with someone about?",
      "If you were a social media filter, what would your effect be?",
      "What’s your most awkward job interview or first-day-at-work moment?",
      "If you could borrow a celebrity’s voice for a day, whose would you pick?",
      "What’s the worst nickname someone tried to give you that didn’t stick?",
      "If you won a trophy for something silly you’re good at, what would it be for?",
      "What’s the most absurd lie you’ve ever believed?",
      "If you could have any exotic pet, which would you choose and what would you name it?"
    ],
    casal: [
      "When did you realize you were falling in love with me?",
      "What memory of us makes you smile the most?",
      "What do you admire most about me that I might not even notice?",
      "If we could travel anywhere in the world together right now, where would we go?",
      "What’s been our favorite date so far?",
      "What makes you feel most loved by me day to day?",
      "What’s a dream you want to make come true with me in the future?",
      "Is there something you’d love for us to do together that we’ve never done?",
      "What song reminds you of us?",
      "What did you think of me on our first date?",
      "What’s the funniest thing that’s ever happened between us?",
      "How do you picture our life 10 years from now?",
      "When did you feel you could trust me 100%?",
      "What would you lovingly change about me, if you could?",
      "What’s our favorite couple tradition, if we have one?",
      "What do you feel you’ve learned from me since we got together?",
      "What’s your favorite way I show affection?",
      "If we could relive one day together, which would you choose?",
      "What do you hope we never lose over time?",
      "What’s the most romantic gesture or declaration that’s happened between us?",
      "When have you felt most proud of me?",
      "What do you think only I can make you feel?",
      "What’s the biggest difference between us that you think makes us complement each other?",
      "If we could create a brand-new tradition just for us, what would it be?",
      "What surprised you about me after we started dating?",
      "What’s a hard time we went through together that made us stronger?",
      "What do you most enjoy doing with me day to day, even if it’s something simple?",
      "If you could give me an experience instead of an object, what would it be?",
      "What word would you use to describe our relationship today?",
      "What do you hope I never change?",
      "What was the first thing you noticed about me?",
      "If we could live anywhere together, where would it be and why?",
      "What makes you feel safe in our relationship?",
      "What’s a goal you’d like us to reach together this year?",
      "What do you think we’ve learned from each other so far?",
      "If we had to write a letter to ourselves 5 years from now, what would it say?",
      "What small gesture of mine meant a lot to you?",
      "What makes you feel closest to me?",
      "If we could relive our first “I love you,” what would be different or the same?",
      "What are you most looking forward to in our next chapter together?"
    ],
    gerais: [
      "If you could instantly learn any skill, which would you choose?",
      "What’s the bravest decision you’ve ever made?",
      "What’s got you most excited these days?",
      "If money weren’t an issue, what would you do with your life?",
      "What book, movie, or show changed the way you see the world?",
      "What’s your biggest fear right now?",
      "If you could have dinner with anyone, living or dead, who would it be?",
      "What advice would you give yourself 5 years ago?",
      "What makes you feel most alive?",
      "What’s been the most challenging moment of your life so far?",
      "If you could live anywhere in the world, where would it be?",
      "What’s a belief you used to hold that you’ve changed your mind about?",
      "What would you do on a day with zero responsibilities?",
      "What do you value most in a friendship?",
      "If you could go back in time, which moment would you relive?",
      "What’s your biggest career dream?",
      "What brings you the most peace?",
      "What’s the best surprise you’ve ever received?",
      "If you could change one thing in the world, what would it be?",
      "What’s the most important lesson life has taught you?",
      "What motivates you to get out of bed every day?",
      "When did you have to step outside your comfort zone?",
      "If you could live in any period of history, which would you choose?",
      "What does success mean to you?",
      "What’s the best lesson a mistake has taught you?",
      "If you could talk to yourself 20 years from now, what would you ask?",
      "What do you do when you need to recharge?",
      "What’s a skill you’d like to develop further?",
      "If you could solve one of the world’s problems, which would you pick?",
      "What inspires you about the people you admire?",
      "When did you have to be brave all on your own?",
      "If you could start something over from scratch, what would it be?",
      "What does freedom mean to you?",
      "What’s the best lesson life taught you outside of school?",
      "If you could stay one age forever, which would you choose?",
      "What do you wish people understood better about you?",
      "When did you feel truly proud of yourself?",
      "If you could know one thing about the future for sure, what would you want to know?",
      "What are you grateful for today?",
      "What advice would you give someone who’s starting something new?"
    ]
  }
};
